### ISSUE TITLE
bug for props

### ISSUE THREAD

**Issue by c0dehigh** [Ordinary-Solutions/ordinary-render-tools#2]
Hello, there are some bugs that the texture of the props cannot be captured in the photos, such as hats, glasses, ears, watches, bracelets.

**Comment by WelaurS** [comment]
Send examples of the items, I will look into

**Comment by c0dehigh** [comment]
[clothes.zip](https://github.com/user-attachments/files/16029330/clothes.zip)

These are some mod files and the exact same problem is the same for base game clothes

The photo output of all files is uv.test.png

**Comment by WelaurS** [comment]
Fixed in https://github.com/Ordinary-Solutions/ordinary-render-tools/commit/23c9e8480c2feb1a42b8ad02a48d041a5b02159d

**Comment by c0dehigh** [comment]
![glasses](https://github.com/Ordinary-Solutions/ordinary-render-tools/assets/86211341/5ecf5ed7-bc53-4f73-bb42-3b22510a9c02)
![hat](https://github.com/Ordinary-Solutions/ordinary-render-tools/assets/86211341/2bfbd30e-f298-49d5-bf63-929640ecd8e0)


The picture is taken well, but the picture is taken from the back of the glasses and hat

**Comment by c0dehigh** [comment]
[pics.zip](https://github.com/user-attachments/files/16046429/pics.zip)

The picture is taken well, but the picture is taken from the back of the glasses and hat
